.\" Process this file with
.\" groff -man -Tascii aj-snapshot.1
.\"
.TH AJ-SNAPSHOT 1 "NOVEMBER 2011" Linux "User Manuals"
.SH NAME
aj-snapshot
.SH SYNOPSIS
.B aj-snapshot \fR[ \fB-adfjqrvx\fR ] [ \fB-i \fIclient_name\fR ] [ \fIFILE\fR ]
.SH DESCRIPTION
.PP
Aj-snapshot is a small program that can be used to make snapshots of the connections made between JACK and/or ALSA clients. Because JACK can provide both audio and MIDI support to programs, aj-snapshot can store both types of connections for JACK. ALSA, on the other hand, only provides routing facilities for MIDI clients.
